

CREATE VIEW [dbo].[Enlaces_Oferta_PrimeraObra00]
AS


SELECT *
FROM OPENQUERY(SIC, '
SELECT CDOFT, MIN(CTRO CONCAT ''-'' CONCAT LEFT(OBRA, 3)) CDOBRA
FROM S44DD901.FICOSCO.CO005BP AS Enlaces
GROUP BY CDOFT')