

CREATE VIEW [dbo].[ObrasActuales-Ofertas]
AS
SELECT CAST(E.CTRO AS int) CTRO, E.CDOFT, LEFT(E.OBRA, 3) AS OBRA, RIGHT(E.OBRA, 2) AS OBRAL, E.AAMMA AS FechaApertura, E.AAMMC AS FechaCierre, 
		Año, Mes, CTR, DSOBR, RSOBR, CDACT, FCONT, CDCLI, PPFAC, PCOST, SRET, SANT, SCOMP, SMP, SMF, SML, SMMO, 
		SMMA, SME, SMT, SMS, SMV, SMI, SMCL, SMH, SMPR, SAP, SAF, SAL, SAMO, SAMA, SAE, SAT, SAS, SAV, SAI, SACL, SAH, SAPR, 
		SOP, SOF, SOL, SOMO, SOMA, SOE, SOT, SOS, SOV, SOI, SOCL, SOH, SOPR, VPC, CC, STOBR, CGC, CDPRO
FROM Enlaces E 
		INNER JOIN ObrasActualesSQL O ON E.CTRO=O.CTR AND E.OBRA=O.OBRA+O.OBRAL