
CREATE VIEW [dbo].[OfertasE_Filtro]
AS
SELECT        CDCEN, CDOFT, DCOF, TVEN
FROM            OPENQUERY(SIC, 'SELECT CDCEN, CDOFT,  DCOF, TVEN FROM S44DD901.ICOMERF.IC09AP WHERE WS10=''E''') AS derivedtbl_1

