CREATE  VIEW [dbo].[Ofertas_Regularizaciones_Provincias]
AS
SELECT     *
FROM         OPENQUERY(SIC, '
SELECT O.CDCEN, O.CDOFT, O.DCOF, O.CDCLI, O.LOCAL, O.PROOF, O.CDAC1, O.CDAC2, O.RPROF, O.IMAOF, O.FECHAA, O.FECHPP, O.PREVE, O.WS10,
		R.IMPRE, R.FECHAR, R.NUMRE, R.CAUS, Pr.NMPRO, CA.CDAut
FROM S44DD901.ICOMERF.IC09AP As O INNER JOIN S44DD901.ICOMERF.IC10AP As R ON O.CDOFT = R.CDOFT
		INNER JOIN S44DD901.ICOMERF.IC05AP as Pr ON O.PROOF = Pr.CDPRO 
		INNER JOIN S44DD901.ICOMERF.IC11AP as CA ON Pr.CDAUT = CA.CDAUT
') 
