
CREATE VIEW [dbo].[OfertasU_Filtro]
AS
SELECT        CDCEN, CDOFT, DCOF, TVEN
FROM            OPENQUERY(SIC, 'SELECT CDCEN, CDOFT,  DCOF, TVEN FROM S44DD901.ICOMERF.IC09AP WHERE WS10=''U''') AS derivedtbl_1

