CREATE VIEW [dbo].[vwContratacionOfertas_AS400_2018]
AS
SELECT       CT AS CodCentro,CODCLIENTE, CODOFER
FROM            OPENQUERY(SIC, 
                         'SELECT DISTINCT  CT , CODOFER, CODCLIENTE FROM S44DD901.ICOMERF.OFERREGU WHERE AÑOAD = 2018 AND ADJUDICADA = ''S'' ')
                          AS Contratacion_AS400_2018