

CREATE VIEW [dbo].[vwEnlaces_ALL]
AS
SELECT *
FROM OPENQUERY(SIC, '
SELECT        CTRO, CDOFT, LEFT(OBRA, 3) AS OBRA, RIGHT(OBRA, 2) AS OBRAL
FROM            S44DD901.FICOSCO.CO005BP AS Enlaces
WHERE        (CDOFT <> ''0000000001'')
UNION
SELECT        CTRO, CDOFT, LEFT(OBRA, 3) AS OBRA, RIGHT(OBRA, 2) AS OBRAL
FROM            S44DD901.FICOSCO.CO005BPH AS EnlacesHistorico
WHERE        (CDOFT <> ''0000000001'' and left(AAMMC,2)=18) 
 ')

