
CREATE VIEW [dbo].[vwEnlaces_ALL_1]
AS
SELECT *
FROM OPENQUERY(SIC, '
SELECT        CTRO, CDOFT, LEFT(OBRA, 3) AS OBRA, RIGHT(OBRA, 2) AS OBRAL
FROM            S44DD901.FICOSCO.CO005BP AS Enlaces
UNION
SELECT        CTRO, CDOFT, LEFT(OBRA, 3) AS OBRA, RIGHT(OBRA, 2) AS OBRAL
FROM            S44DD901.FICOSCO.CO005BPH AS EnlacesHistorico
WHERE        left(AAMMC,2)=18
 ')