CREATE VIEW [dbo].[vwWEB_OFERTAS_CA_SinAdjudicacion_SinObras_iSeries]
AS

SELECT *
FROM OPENQUERY(SIC,'
SELECT   OFCA.CDOFT CDOFT_OF, OFCA.ADELE, Enlaces.CDOFT CDOFT_En
FROM  S44DD901.ICOMERF.IC09AP As OFCA LEFT OUTER JOIN S44DD901.FICOSCO.CO005BP AS Enlaces ON
		OFCA.CDCEN = Enlaces.CTRO AND OFCA.CDOFT = Enlaces.CDOFT
')