CREATE TABLE [dbo].[IC09AP] (
    [id]      INT           IDENTITY (1, 1) NOT NULL,
    [Usuario] VARCHAR (50)  NOT NULL,
    [CDCEN]   VARCHAR (3)   NOT NULL,
    [CDOFT]   VARCHAR (10)  NOT NULL,
    [FECHAA]  NUMERIC (7)   NOT NULL,
    [AñoAA]   INT           NOT NULL,
    [MesAA]   INT           NOT NULL,
    [DCOF]    VARCHAR (100) NULL,
    [CDCLI]   VARCHAR (8)   NOT NULL,
    [LOCAL]   VARCHAR (100) NULL,
    [PROOF]   VARCHAR (50)  NULL,
    [IMAOF]   NUMERIC (9)   NULL,
    [CDAC1]   VARCHAR (2)   NOT NULL,
    [CDAC2]   VARCHAR (2)   NOT NULL,
    [DECOF]   VARCHAR (50)  NULL,
    [RPROF]   VARCHAR (50)  NULL,
    [FECHPP]  NUMERIC (7)   NULL,
    [PREVE]   NUMERIC (9)   NULL,
    [FECHAD]  NUMERIC (7)   NULL,
    [AñoAD]   INT           NULL,
    [MesAD]   INT           NULL,
    [ADELE]   VARCHAR (1)   NOT NULL,
    [PREAD]   NUMERIC (9)   NULL,
    [TCOS]    NUMERIC (9)   NULL,
    [TVEN]    NUMERIC (9)   NULL,
    [WS10]    VARCHAR (1)   NULL,
    [DESPRO]  VARCHAR (100) NULL,
    [BAJA]    VARCHAR (1)   NULL,
    CONSTRAINT [PK_IC09AP_Id] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_IC09AP_Usuario]
    ON [dbo].[IC09AP]([Usuario] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC09AP_CDCEN]
    ON [dbo].[IC09AP]([CDCEN] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC09AP_AñoAA_MesAA]
    ON [dbo].[IC09AP]([AñoAA] ASC, [MesAA] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC09AP_AñoAD_MesAD]
    ON [dbo].[IC09AP]([AñoAD] ASC, [MesAD] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC09AP_ADELE]
    ON [dbo].[IC09AP]([ADELE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC09AP_CDCLI]
    ON [dbo].[IC09AP]([CDCLI] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC09AP_CDAC1_CDAC2]
    ON [dbo].[IC09AP]([CDAC1] ASC, [CDAC2] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC09AP_CDOFT]
    ON [dbo].[IC09AP]([CDOFT] ASC);

