CREATE TABLE [dbo].[IC10AP] (
    [id]      INT          IDENTITY (1, 1) NOT NULL,
    [Usuario] VARCHAR (50) NOT NULL,
    [CDCEN]   VARCHAR (3)  NOT NULL,
    [CDOFT]   VARCHAR (20) NOT NULL,
    [IMPRE]   NUMERIC (9)  NULL,
    [AR]      INT          NOT NULL,
    [MR]      INT          NOT NULL,
    CONSTRAINT [PK_IC10AP_Id] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_IC10AP_Usuario]
    ON [dbo].[IC10AP]([Usuario] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC10AP_CDCEN]
    ON [dbo].[IC10AP]([CDCEN] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC10AP_CDOFT]
    ON [dbo].[IC10AP]([CDOFT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC10AP_AR_MR]
    ON [dbo].[IC10AP]([AR] ASC, [MR] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IC10AP]
    ON [dbo].[IC10AP]([Usuario] ASC)
    INCLUDE([CDCEN], [CDOFT], [IMPRE], [AR], [MR]);

