CREATE TABLE [dbo].[OFERREGU] (
    [id]           INT           IDENTITY (1, 1) NOT NULL,
    [Usuario]      VARCHAR (50)  NOT NULL,
    [CT]           VARCHAR (3)   NOT NULL,
    [MERCADO]      VARCHAR (13)  NOT NULL,
    [CODOFER]      VARCHAR (10)  NOT NULL,
    [DESOFER]      VARCHAR (100) NULL,
    [REG]          NUMERIC (2)   NULL,
    [CAUSA]        VARCHAR (50)  NULL,
    [LOCALIDAD]    VARCHAR (50)  NULL,
    [CODPROVINCIA] VARCHAR (2)   NULL,
    [NOMPROVINCIA] VARCHAR (30)  NULL,
    [CODCLIENTE]   VARCHAR (8)   NULL,
    [NOMCLIENTE]   VARCHAR (50)  NULL,
    [ACT1]         VARCHAR (2)   NOT NULL,
    [ACT2]         VARCHAR (2)   NOT NULL,
    [RESPONSABLE]  VARCHAR (3)   NULL,
    [AÑOGRAB]      NUMERIC (4)   NULL,
    [MESGRAB]      NUMERIC (2)   NULL,
    [IMPAPROX]     NUMERIC (9)   NULL,
    [AÑOPRES]      NUMERIC (4)   NULL,
    [MESPRES]      NUMERIC (2)   NULL,
    [IMPPRES]      NUMERIC (9)   NULL,
    [ADJUDICADA]   VARCHAR (1)   NULL,
    [AÑOAD]        NUMERIC (4)   NULL,
    [MESAD]        NUMERIC (2)   NULL,
    [IMPAD]        NUMERIC (9)   NULL,
    [TIPO]         CHAR (1)      NULL,
    [OFERTAR]      CHAR (2)      NULL,
    [TOTCOSTOS]    NUMERIC (9)   NULL,
    [IMPTOTAL]     NUMERIC (9)   NULL,
    [CLIENTPROV]   CHAR (30)     NULL,
    [BAJA]         CHAR (1)      NULL,
    [AI]           VARCHAR (2)   NULL,
    [ORIGEN]       VARCHAR (1)   NULL,
    CONSTRAINT [PK_OFERREGU_ID] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_OFERREGU_USUARIO_ADJUDICADA_AÑOAD]
    ON [dbo].[OFERREGU]([Usuario] ASC, [ADJUDICADA] ASC, [AÑOAD] ASC)
    INCLUDE([CT], [CODOFER], [CODCLIENTE]);


GO
CREATE NONCLUSTERED INDEX [IX_OFERREGU_CT]
    ON [dbo].[OFERREGU]([CT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_OFERREGU_ACT1_ACT2]
    ON [dbo].[OFERREGU]([ACT1] ASC, [ACT2] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_OFERREGU_CODOFER]
    ON [dbo].[OFERREGU]([CODOFER] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_OFERREGU_AÑOAD_MESAD]
    ON [dbo].[OFERREGU]([AÑOAD] ASC, [MESAD] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_OFERREGU_CODCLIENTE]
    ON [dbo].[OFERREGU]([CODCLIENTE] ASC);

