CREATE TABLE [dbo].[WEB_OFERTACION] (
    [id]      INT          IDENTITY (1, 1) NOT NULL,
    [Usuario] VARCHAR (50) NOT NULL,
    [CDCEN]   NUMERIC (3)  NOT NULL,
    [CDOFT]   NUMERIC (10) NOT NULL,
    [FECHAA]  NUMERIC (7)  NOT NULL,
    [IMAOF]   NUMERIC (9)  CONSTRAINT [DF_WEB_OFERTACION_IMAOF] DEFAULT ((0)) NOT NULL,
    [FECHPP]  NUMERIC (7)  NOT NULL,
    [PREVE]   NUMERIC (9)  CONSTRAINT [DF_WEB_OFERTACION_PREVE] DEFAULT ((0)) NOT NULL,
    [FECHAD]  NUMERIC (7)  NOT NULL,
    [ADELE]   CHAR (1)     NOT NULL,
    [PREAD]   NUMERIC (9)  CONSTRAINT [DF_WEB_OFERTACION_PREAD] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_WEB_OFERTACION] PRIMARY KEY CLUSTERED ([id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_Usuario]
    ON [dbo].[WEB_OFERTACION]([Usuario] ASC);

