
--[dbo].[spSincronizar_ObrasActualesSQL] 2014,12

CREATE PROCEDURE [dbo].[spSincronizar_ObrasActualesSQL]
	@pAño int,
	@pMes int 	
AS
BEGIN	
	
	BEGIN TRY
	
		DELETE FROM dbo.ObrasActualesSQL WHERE Año=@pAño AND Mes=@pMes

		INSERT INTO [RP_SIC].[dbo].[ObrasActualesSQL]( Año, Mes, CTR, OBRA, OBRAL, DSOBR, RSOBR, CDACT, FCONT, CDCLI, PPFAC, PCOST, SRET, SANT, SCOMP, SMP, SMF, SML, SMMO, SMMA, SME, SMT, SMS,SMV, SMI, SMCL, SMH, SMPR, SAP, SAF, SAL, SAMO, SAMA, SAE, SAT, SAS, SAV, SAI, SACL, SAH, SAPR, SOP, SOF, SOL, SOMO, SOMA, SOE, SOT, SOS, SOV, SOI, SOCL, SOH, SOPR, VPC, CC, STOBR, CGC, CDPRO)
		SELECT  @pAño, @pMes,CTR, OBRA, OBRAL, DSOBR, RSOBR, CDACT, FCONT, CDCLI, PPFAC, PCOST, SRET, SANT, SCOMP, SMP, SMF, SML, SMMO, SMMA, SME, SMT, SMS, SMV, SMI, SMCL, SMH, SMPR, SAP, SAF, SAL, SAMO, SAMA, SAE, SAT, SAS, SAV, SAI, SACL, SAH, SAPR, SOP, SOF, SOL, SOMO, SOMA, SOE, SOT, SOS, SOV, SOI, SOCL, SOH, SOPR, VPC, CC, STOBR, CGC, CDPRO
		FROM dbo.Obras
		--FROM [dbo].[Obras_Diciembre_2014]

		select 0 -- NO ERROR
   
	END TRY
	BEGIN CATCH
		select ERROR_NUMBER ()
	END CATCH
    
END
