CREATE FUNCTION [dbo].[fnContratacion_AS400] (@pAño int, @pUsuario varchar(15))
RETURNS
 @OFERREGU TABLE (
	AÑOAD int,
	MESAD int,
	CT int,
	CODOFER int,
	DESOFER varchar(100),
	CODCLIENTE varchar(8),
	IMPAD numeric(9,0)
 )
AS
BEGIN

  INSERT INTO @OFERREGU(AÑOAD,MESAD,CT,CODOFER,DESOFER,CODCLIENTE,IMPAD) 
  SELECT AÑOAD,MESAD,CT,CODOFER,DESOFER,CODCLIENTE,IMPAD FROM OFERREGU WHERE AÑOAD=@pAño AND ADJUDICADA = 'S' AND Usuario=@pUsuario
  
 RETURN

END
