CREATE FUNCTION [dbo].[fnDescripcionOfertaAS400] (@pCODOFER int)
RETURNS varchar(100)
AS  
BEGIN

	DECLARE @DESOFER as varchar(100)
	DECLARE @vSQL as varchar(100)

	SET @vSQL='SELECT * FROM S44DD901.ICOMERF.OFERREGU WHERE ADJUDICADA = ''S'' AND CODOFER = 1450900019 '--'SELECT * FROM S44DD901.ICOMERF.OFERREGU WHERE ADJUDICADA = ''S'' AND CODOFER =' + @pCODOFER  

	SELECT TOP 1 @DESOFER=DESOFER
	FROM OPENQUERY(SIC, 'SELECT * FROM S44DD901.ICOMERF.OFERREGU WHERE ADJUDICADA = ''S'' AND CODOFER = 1450900019 ' ) AS Contratacion_AS400_2018
	

	RETURN(@DESOFER)

END