
create FUNCTION [dbo].[fnEnlacesALL] (@pUno bit, @pUsuario varchar(10))
RETURNS
 @CO005BPALL TABLE (
	  CTRO char(3),
	  OBRA char(3),
	  OBRAL char(2),
	  CDOFT numeric(10,0)
 )
AS
BEGIN

  IF @pUno=1
	  INSERT INTO @CO005BPALL(CTRO,OBRA,OBRAL,CDOFT) 
	  SELECT CTRO,OBRA,OBRAL,CDOFT FROM CO005BP WHERE Usuario=@pUsuario
	  UNION
	  SELECT CTRO,OBRA,OBRAL,CDOFT FROM CO005BPH WHERE Usuario=@pUsuario
  ELSE
	  INSERT INTO @CO005BPALL(CTRO,OBRA,OBRAL,CDOFT) 
	  SELECT CTRO,OBRA,OBRAL,CDOFT FROM CO005BP WHERE Usuario=@pUsuario AND CDOFT<>1
	  UNION
	  SELECT CTRO,OBRA,OBRAL,CDOFT FROM CO005BPH WHERE Usuario=@pUsuario AND CDOFT<>1
  
 RETURN

END