CREATE LOGIN [UsuDataLakeCIC]
    WITH PASSWORD = N'rbztx~Epzquhp|YLqP?whxabmsFT7_&#$!~<c:jl>zz;{hj}', SID = 0x8119E9AEB0D4034F968ECB0EC20F17E3, DEFAULT_DATABASE = [RP_SIC], DEFAULT_LANGUAGE = [Español], CHECK_POLICY = OFF;

