CREATE LOGIN [usuELECSIG]
    WITH PASSWORD = N'~wVoglm{eM!xc{uvirbuJKozmsFT7_&#$!~<orisy{Vhrlkx', SID = 0x5B6BF0BE1BFD5E46A75823C8E5936170, DEFAULT_DATABASE = [RP_SIC], DEFAULT_LANGUAGE = [Español], CHECK_POLICY = OFF;

